version: '3.8'

services:
  bot:
    build: .
    container_name: upwork-job-delivery-bot
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - upwork_bot_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 141288root
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - upwork_bot_network

volumes:
  mongo-data:


networks:
  upwork_bot_network:
    driver: bridge
